### ISSUE TITLE
change the label on the homrpage table "proving time" to "time to proof"

### ISSUE THREAD

**Issue by nloureiro** [ethproofs/ethproofs#97]
![Screen Shot 2024-11-28 01 53 24 PM](https://github.com/user-attachments/assets/a0e0a384-4ba8-4d5c-8794-bebc60d7c3d1)

**Comment by wackerow** [comment]
<img width="556" alt="image" src="https://github.com/user-attachments/assets/f64c8206-94e0-4444-86a7-1c5da353abb7">

Feel free to reopen if I'm missing something
